### ISSUE TITLE
[GUI] Error when saving plot snapshot  with McaWindow

### ISSUE THREAD

**Issue by PiRK** [vasole/pymca#271]
When trying to save as Graphics SVG/PNG/EPS:
```
Traceback (most recent call last):
  File "/users/knobel/.local/lib/python2.7/site-packages/PyMca5/PyMcaGui/pymca/McaWindow.py", line 1351, in _saveIconSignal
    self.graphicsSave(specFile)
AttributeError: 'McaWindow' object has no attribute 'graphicsSave'
```

When attempting to save as Widget PNG/JPG:
```
type object 'QPixmap' has no attribute 'grabWidget'   File "/users/knobel/.local/lib/python2.7/site-packages/PyMca5/PyMcaGui/pymca/McaWindow.py", line 1340, in _saveIconSignal
    pixmap = qt.QPixmap.grabWidget(self.getWidgetHandle())
```

**Comment by vasole** [comment]
The first of the issues was not fixed.
