### ISSUE TITLE
[install] issue on windows

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#460]
I encountered a problem with pip install from source on Windows:

```powershell
C:\projects\pymca>py -3.6 -m pip install .
C:\projects>cd ..
C:\projects>py -3.6 -m PyMca5.PyMcaGui.pymca.PyMcaMain
Traceback (most recent call last):
  File "C:\Users\denolf\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\denolf\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\denolf\AppData\Roaming\Python\Python36\site-packages\PyMca5\__init__.py", line 35, in <module>
    from PyMca5.PyMcaDataDir import PYMCA_DATA_DIR
  File "C:\Users\denolf\AppData\Roaming\Python\Python36\site-packages\PyMca5\PyMcaDataDir.py", line 35
    PYMCA_DATA_DIR = 'C:\Users\denolf\AppData\Roaming\Python\Python36\site-packages\PyMca5\PyMcaData'
                    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by vasole** [comment]
It is really weird. I would expect to happen everywhere or nowhere. The directory is reported by Python itself. Probably one should just replace '\' by '\\' in setup.py under windows.

**Comment by vasole** [comment]
Please, do nothing. I take a look tomorrow.

**Comment by vasole** [comment]
Thanks a lot. To reproduce the issue I had to make a Python installation for a single user. That way the \U (from \Users instead of \P from \Program) was triggering the problem.
