### ISSUE TITLE
[pyside2] Destroyed while thread is still running

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#565]
Error occurs with python 2.7.15, Ubuntu Xenial, pyside2 (I ran it in on a virtual machine that mimics Travis)

This produces the errors:

````python
python -m unittest -v PyMca5.tests.PyMcaBatchTest.testPyMcaBatch
````

Errors:

````bash
testCommand (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testFastFitEdfMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testFastFitHdf5Map (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testFastFitSpecMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowFitEdfMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowFitHdf5Map (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowFitSpecMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowMultiFitEdfMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... 
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
Aborted (core dumped)
Aborted (core dumped)
INFO:PyMca5.PyMcaPhysics.xrf.McaAdvancedFitBatch:Memory allocated
INFO:PyMca5.PyMcaPhysics.xrf.McaAdvancedFitBatch:Memory allocated
ok
testSlowMultiFitHdf5Map (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... 
QThread: Destroyed while thread is still running
Aborted (core dumped)
QThread: Destroyed while thread is still running
Aborted (core dumped)
ok
testSlowMultiFitSpecMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... 
QThread: Destroyed while thread is still running
Aborted (core dumped)
INFO:PyMca5.PyMcaPhysics.xrf.McaAdvancedFitBatch:Memory allocated
INFO:PyMca5.PyMcaPhysics.xrf.McaAdvancedFitBatch:Memory allocated
ok
testSlowRoiFitEdfMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowRoiFitHdf5Map (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSlowRoiFitSpecMap (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
testSubCommands (PyMca5.tests.PyMcaBatchTest.testPyMcaBatch) ... ok
````

Core dump

````bash
#0  0x00007f0aad2f6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f0aad2f802a in __GI_abort () at abort.c:89
#2  0x00007f0aa0b76b4c in QMessageLogger::fatal(char const*, ...) const ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/Qt/lib/libQt5Core.so.5
#3  0x00007f0aa0b9461c in QThread::~QThread() ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/Qt/lib/libQt5Core.so.5
#4  0x00007f0aa1755191 in QThreadWrapper::~QThreadWrapper() ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/QtCore.so
#5  0x00007f0aa12c8909 in PySide::destructionVisitor(SbkObject*, void*) ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/libpyside2-python2.7.so.5.13
#6  0x00007f0aa1c1f652 in Shiboken::BindingManager::visitAllPyObjects(void (*)(SbkObject*, void*), void*) ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/shiboken2/libshiboken2-python2.7.so.5.13
#7  0x00007f0aa12c90c1 in PySide::destroyQCoreApplication() ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/libpyside2-python2.7.so.5.13
#8  0x00007f0aa12ca260 in PySide::runCleanupFunctions() ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/libpyside2-python2.7.so.5.13
#9  0x00007f0aa179b1b5 in SbkQtCoreModule___moduleShutdown(_object*) ()
   from /home/travis/virtualenv/py27pymca/lib/python2.7/site-packages/PySide2/QtCore.so
#10 0x00007f0aad9b7aad in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7ffe973a0558, 
    func=0x7f0aa1bb95f0) at ../Python/ceval.c:4683
#11 PyEval_EvalFrameEx (f=f@entry=0x7f0a8bcda430, throwflag=throwflag@entry=0) at ../Python/ceval.c:3048
#12 0x00007f0aad9bab4c in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, 
    args=args@entry=0x7f0aade8d068, argcount=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at ../Python/ceval.c:3604
#13 0x00007f0aad92f99c in function_call (func=0x7f0aabeb9398, arg=0x7f0aade8d050, kw=0x0) at ../Objects/funcobject.c:523
#14 0x00007f0aad8fd083 in PyObject_Call (func=func@entry=0x7f0aabeb9398, arg=arg@entry=0x7f0aade8d050, kw=<optimized out>)
    at ../Objects/abstract.c:2547
#15 0x00007f0aad9b0c17 in PyEval_CallObjectWithKeywords (func=func@entry=0x7f0aabeb9398, arg=0x7f0aade8d050, arg@entry=0x0, 
    kw=kw@entry=0x0) at ../Python/ceval.c:4241
#16 0x00007f0aad9e03f7 in call_sys_exitfunc () at ../Python/pythonrun.c:1765
#17 Py_Finalize () at ../Python/pythonrun.c:430
#18 0x00007f0aad9f6ec4 in Py_Main (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:670
#19 0x00007f0aad2e1830 in __libc_start_main (main=0x4006d0 <main>, argc=29, argv=0x7ffe973a0988, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe973a0978) at ../csu/libc-start.c:291
#20 0x0000000000400709 in _start ()
````

**Comment by vasole** [comment]
We can suppress the PySide2 testing for Python2 because it only makes sense for Python3.

However I find weird that we have a core dump but the test is still successful.

**Comment by vasole** [comment]
Sorry click on wrong place.
