### ISSUE TITLE
[HDF5] Handle broken NXentry links

### ISSUE THREAD

**Issue by woutdenolf** [vasole/pymca#603]
`HDF5Stack1D` dataset selection gives following errors when there are broken NXentry links:

```bash
Traceback (most recent call last):
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/PyMcaMain.py", line 1444, in __roiImaging
    widget.loadStack()
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/QStackWidget.py", line 581, in loadStack
    stack = self.stackSelector.getStack()
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/StackSelector.py", line 106, in getStack
    stack = QHDF5Stack1D.QHDF5Stack1D(filelist)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/QHDF5Stack1D.py", line 51, in __init__
    dtype=dtype)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaIO/HDF5Stack1D.py", line 67, in __init__
    self.loadFileList(filelist, selection, scanlist)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaIO/HDF5Stack1D.py", line 97, in loadFileList
    if isinstance(tmpHdf["/"+key], h5py.Group):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/rnice8/pymca/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (unable to open external file, external link file name = '/dls/i18/data/2019/sp23348-1/i18-158811.nxs')"
```

```bash
Traceback (most recent call last):
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/PyMcaMain.py", line 1444, in __roiImaging
    widget.loadStack()
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/QStackWidget.py", line 581, in loadStack
    stack = self.stackSelector.getStack()
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/StackSelector.py", line 106, in getStack
    stack = QHDF5Stack1D.QHDF5Stack1D(filelist)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaGui/pymca/QHDF5Stack1D.py", line 51, in __init__
    dtype=dtype)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaIO/HDF5Stack1D.py", line 67, in __init__
    self.loadFileList(filelist, selection, scanlist)
  File "/mntdirect/_data_id21_inhouse/wout/dev/pymca/build/lib.linux-x86_64-3.6/PyMca5/PyMcaIO/HDF5Stack1D.py", line 443, in loadFileList
    if hasattr(hdf[tmpPath], "keys"):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mntdirect/_data_id21_inhouse/wout/dev/virtualenvs/rnice8/pymca/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (unable to open external file, external link file name = '/dls/i18/data/2019/sp23348-1/i18-158811.nxs')"
```

**Comment by vasole** [comment]
closed by #604
