### ISSUE TITLE
Advanced alignment plugin crashes when calculating shifts

### ISSUE THREAD

**Issue by kkummer** [vasole/pymca#730]
Trying to calculate the shift between two curves with the Advanced alignment plugin causes the plugin to crash. The problem is in line 1007 of PyMca5/PyMcaPlugins/AdvancedAlignmentScanPlugin.py.

1003        # Determine average spaceing between Datapoints
1004        step = numpy.average(numpy.diff(activeX))
1005         xmin, xmax = self.getXLimits([x for (x,y,leg,info) in curves],
1006                                     overlap=False)
1007        num  = factor * numpy.ceil((xmax-xmin)/step)
1008
1009        # Create equidistant x-range, exclude first and last point
1010        xeq = numpy.linspace(xmin, xmax, num, endpoint=False)[:-1]

numpy.linspace requires an integer type for the num argument, but a float type is passed by the advanced alignment plugin. I think the bug did not show up for older versions of numpy because they tried to cast num into an integer type before raising an exception?

--- Full error message -----------------------------------

Traceback (most recent call last):
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\PyMca5\PyMcaPlugins\AdvancedAlignmentScanPlugin.py", line 296, in triggerCalculateShift
    llist, ddict = self.plugin.calculateShifts()
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\PyMca5\PyMcaPlugins\AdvancedAlignmentScanPlugin.py", line 559, in calculateShifts
    self.shiftList, self.shiftDict = self.alignmentMethod()
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\PyMca5\PyMcaPlugins\AdvancedAlignmentScanPlugin.py", line 720, in calculateShiftsFFT
    curves = self.interpolate()
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\PyMca5\PyMcaPlugins\AdvancedAlignmentScanPlugin.py", line 1010, in interpolate
    xeq = numpy.linspace(xmin, xmax, num, endpoint=False)[:-1]
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\Users\kkummer\AppData\Local\Continuum\miniconda3\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by vasole** [comment]
Thanks! Very timely issue. I intend to make a release very soon. #731 (when merged) should fix it.
