### ISSUE TITLE
Error in RegularMeshPlugin

### ISSUE THREAD

**Issue by cpt-majkel** [vasole/pymca#969]
Hi,

We have noticed a strange error in RegularMeshPlugin. 
We are using `.dat` format and RegularMeshPlugin to visualize mesh scans. Recently, we have upgraded PyMca from version `5.3.1` up to `5.5.5` and noticed a strange bug (same behaviour is with the latest `5.8.1`, with `5.3.1` it was working well). 

How to reproduce?

- Load mesh (examples in attachment, scans 3,4,5 are mesh data we gathered)
- Choose scan 3,4 or 5 
- On X choose SY motor, and on Y d5 values
- use RegularMeshPlugin to visualize - everything works

<img width="1280" alt="pymca1" src="https://user-images.githubusercontent.com/24622343/222748630-2dd456d7-058e-40c1-84f9-48c241105e03.PNG">

- switch to other scan in 3-5 and use RegularMeshPlugin again - there is an error

<img width="1279" alt="pymca2" src="https://user-images.githubusercontent.com/24622343/222748720-72f9cbcd-084a-4a98-a224-c669c747e9d2.PNG">

```
Traceback (most recent call last):
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaGui/plotting/PlotWindow.py", line 1022, in _pluginClicked
    self.pluginInstanceDict[key].applyMethod(methods[idx])
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaPlugins/RegularMeshPlugin.py", line 80, in applyMethod
    self.methodDict[name][0]()
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaPlugins/RegularMeshPlugin.py", line 182, in _convert
    deltaY))
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaGui/plotting/MaskImageWidget.py", line 1231, in setImageData
    self.plotImage(update = True)
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaGui/plotting/MaskImageWidget.py", line 1298, in plotImage
    self.__applyMaskToImage()
  File "/home/Michal.Piekarski/miniconda3/envs/pymca2/lib/python3.6/site-packages/PyMca5/PyMcaGui/plotting/MaskImageWidget.py", line 1566, in __applyMaskToImage
    alteration)
ValueError: operands could not be broadcast together with shapes (22,19) (17,12) 
```

- repeating previous step always generates same error
- only way to visualize it is to restart application and choose this mesh as the first one

Cheers,
Michal
SOLARIS

[bl_mesh.zip](https://github.com/vasole/pymca/files/10882886/bl_mesh.zip)

**Comment by vasole** [comment]
The problem was happening when plotting meshes of different sizes.

#970 should correct the issue.

Just in case, you can also visualize irregular meshes or scatter plots turning 2D on and selecting two counters for the axes (see image below).

![image](https://user-images.githubusercontent.com/5636251/222757474-db01d11f-b22b-4b67-8100-6a04ec53dd16.png)

**Comment by vasole** [comment]
Correction already included in master branch.

Thanks for the bug report!
